CREATE TABLE "INPATIENT_2012_DATA" 
   (	"ID" NUMBER,
   "DRG_DEFINITION" VARCHAR2(120 BYTE), 
	"PROVIDER_ID" VARCHAR2(10 BYTE), 
	"PROVIDER_NAME" VARCHAR2(120 BYTE), 
	"PROVIDER_STREET_ADDRESS" VARCHAR2(150 BYTE), 
	"PROVIDER_CITY" VARCHAR2(50 BYTE), 
	"PROVIDER_STATE" VARCHAR2(2 BYTE), 
	"PROVIDER_ZIP_CODE" VARCHAR2(5 BYTE), 
	"HRR_DESCRIPTION" VARCHAR2(100 BYTE), 
	"TOTAL_DISCHARGES" NUMBER, 
	"AVERAGE_COVERED_CHARGES" FLOAT(126), 
	"AVERAGE_TOTAL_PAYMENTS" FLOAT(126), 
	"AVERAGE_MEDICARE_PAYMENTS" FLOAT(126),
  "MCPAYMENT_CHARGEDAMT_RATIO" FLOAT(126),
  "TOT_PAYMENT_CHARGEDAMT_RATIO" FLOAT(126),
  "MCPAYMENT_TOTALPAY_RATIO" FLOAT(126),
  "DISCHARGE_PCT" FLOAT(126),
  "SUBMITTED_CHRG_VS_DRG_AGGR" FLOAT(126)
   ) ;
   
insert into INPATIENT_2012_DATA
select 
ROWNUM,
INPATIENT_2012_DATA_B.DRG_DEFINITION,
INPATIENT_2012_DATA_B.PROVIDER_ID,
INPATIENT_2012_DATA_B.PROVIDER_NAME,
INPATIENT_2012_DATA_B.PROVIDER_STREET_ADDRESS,
INPATIENT_2012_DATA_B.PROVIDER_CITY,
INPATIENT_2012_DATA_B.PROVIDER_STATE,
INPATIENT_2012_DATA_B.PROVIDER_ZIP_CODE,
INPATIENT_2012_DATA_B.HRR_DESCRIPTION,
INPATIENT_2012_DATA_B.TOTAL_DISCHARGES,
INPATIENT_2012_DATA_B.AVERAGE_COVERED_CHARGES,
INPATIENT_2012_DATA_B.AVERAGE_TOTAL_PAYMENTS,
INPATIENT_2012_DATA_B.AVERAGE_MEDICARE_PAYMENTS,
INPATIENT_2012_DATA_B.AVERAGE_MEDICARE_PAYMENTS/INPATIENT_2012_DATA_B.AVERAGE_COVERED_CHARGES,
INPATIENT_2012_DATA_B.AVERAGE_TOTAL_PAYMENTS/INPATIENT_2012_DATA_B.AVERAGE_COVERED_CHARGES,
INPATIENT_2012_DATA_B.AVERAGE_MEDICARE_PAYMENTS/INPATIENT_2012_DATA_B.AVERAGE_TOTAL_PAYMENTS,
INPATIENT_2012_DATA_B.TOTAL_DISCHARGES/INPATIENT_2012_NATIONAL_DATA.TOTAL_DISCHARGES,
INPATIENT_2012_DATA_B.AVERAGE_COVERED_CHARGES/INPATIENT_2012_STATE_DATA.AVERAGE_COVERED_CHARGES
from INPATIENT_2012_DATA_B, INPATIENT_2012_NATIONAL_DATA, INPATIENT_2012_STATE_DATA
where INPATIENT_2012_DATA_B.DRG_DEFINITION = INPATIENT_2012_NATIONAL_DATA.DRG_DEFINITION and
INPATIENT_2012_DATA_B.DRG_DEFINITION = INPATIENT_2012_STATE_DATA.DRG_DEFINITION and
INPATIENT_2012_DATA_B.PROVIDER_STATE = INPATIENT_2012_STATE_DATA.PROVIDER_STATE;
drop table INPATIENT_2012_DATA_B;
commit;