 CREATE TABLE "INPATIENT_2012_DATA_B" 
   (	"DRG_DEFINITION" VARCHAR2(120 BYTE), 
	"PROVIDER_ID" VARCHAR2(10 BYTE), 
	"PROVIDER_NAME" VARCHAR2(120 BYTE), 
	"PROVIDER_STREET_ADDRESS" VARCHAR2(150 BYTE), 
	"PROVIDER_CITY" VARCHAR2(50 BYTE), 
	"PROVIDER_STATE" VARCHAR2(2 BYTE), 
	"PROVIDER_ZIP_CODE" VARCHAR2(5 BYTE), 
	"HRR_DESCRIPTION" VARCHAR2(100 BYTE), 
	"TOTAL_DISCHARGES" NUMBER, 
	"AVERAGE_COVERED_CHARGES" FLOAT(126), 
	"AVERAGE_TOTAL_PAYMENTS" FLOAT(126), 
	"AVERAGE_MEDICARE_PAYMENTS" FLOAT(126)
   ) ;
commit;