select PLACE_OF_SERVICE, HCPCS_CODE from PHYSICIAN_HCPCS_AGGREGATE where
NPPES_PROVIDER_STATE_DESC = 'Overall' and NUMBER_OF_PROVIDERS >= 100 and 
P50_MEDICARE_ALLOWED_AMT >= 1000 order by PLACE_OF_SERVICE,
P50_MEDICARE_ALLOWED_AMT desc;

