CREATE TABLE "PHYSICIAN_AND_OTHER_SUPPLIER_C" 
   (	"ID" NUMBER, 
	"NPI" VARCHAR2(10 BYTE), 
	"NPPES_PROVIDER_LAST_ORG_NAME" VARCHAR2(70 BYTE), 
	"NPPES_PROVIDER_FIRST_NAME" VARCHAR2(20 BYTE), 
	"NPPES_PROVIDER_MI" VARCHAR2(1 BYTE), 
	"NPPES_CREDENTIALS" VARCHAR2(20 BYTE), 
	"NPPES_PROVIDER_GENDER" VARCHAR2(1 BYTE), 
	"NPPES_ENTITY_CODE" VARCHAR2(1 BYTE), 
	"NPPES_PROVIDER_STREET1" VARCHAR2(55 BYTE), 
	"NPPES_PROVIDER_STREET2" VARCHAR2(55 BYTE), 
	"NPPES_PROVIDER_CITY" VARCHAR2(40 BYTE), 
	"NPPES_PROVIDER_ZIP" VARCHAR2(20 BYTE), 
	"NPPES_PROVIDER_STATE" VARCHAR2(2 BYTE), 
	"NPPES_PROVIDER_COUNTRY" VARCHAR2(2 BYTE), 
	"PROVIDER_TYPE" VARCHAR2(43 BYTE), 
	"MEDICARE_PARTICIPATION_INDICAT" VARCHAR2(1 BYTE), 
	"PLACE_OF_SERVICE" VARCHAR2(1 BYTE), 
	"HCPCS_CODE" VARCHAR2(5 BYTE), 
	"HCPCS_DESCRIPTION" VARCHAR2(30 BYTE), 
	"LINE_SRVC_CNT" NUMBER(*,0), 
	"BENE_UNIQUE_CNT" NUMBER(*,0), 
	"BENE_DAY_SRVC_CNT" NUMBER(*,0), 
	"AVERAGE_MEDICARE_ALLOWED_AMT" FLOAT(126), 
	"STDEV_MEDICARE_ALLOWED_AMT" FLOAT(126), 
	"AVERAGE_SUBMITTED_CHRG_AMT" FLOAT(126), 
	"STDEV_SUBMITTED_CHRG_AMT" FLOAT(126), 
	"AVERAGE_MEDICARE_PAYMENT_AMT" FLOAT(126), 
	"STDEV_MEDICARE_PAYMENT_AMT" FLOAT(126), 
	"LINE_SRVC_PCT" FLOAT(26)
   )  ;

commit;
insert into PHYSICIAN_AND_OTHER_SUPPLIER_C
select 
ROWNUM,
PHYSICIAN_AND_OTHER_SUPPLIER_B.NPI,
PHYSICIAN_AND_OTHER_SUPPLIER_B.NPPES_PROVIDER_LAST_ORG_NAME,
PHYSICIAN_AND_OTHER_SUPPLIER_B.NPPES_PROVIDER_FIRST_NAME,
PHYSICIAN_AND_OTHER_SUPPLIER_B.NPPES_PROVIDER_MI,
PHYSICIAN_AND_OTHER_SUPPLIER_B.NPPES_CREDENTIALS,
PHYSICIAN_AND_OTHER_SUPPLIER_B.NPPES_PROVIDER_GENDER,
PHYSICIAN_AND_OTHER_SUPPLIER_B.NPPES_ENTITY_CODE,
PHYSICIAN_AND_OTHER_SUPPLIER_B.NPPES_PROVIDER_STREET1,
PHYSICIAN_AND_OTHER_SUPPLIER_B.NPPES_PROVIDER_STREET2,
PHYSICIAN_AND_OTHER_SUPPLIER_B.NPPES_PROVIDER_CITY,
PHYSICIAN_AND_OTHER_SUPPLIER_B.NPPES_PROVIDER_ZIP,
PHYSICIAN_AND_OTHER_SUPPLIER_B.NPPES_PROVIDER_STATE,
PHYSICIAN_AND_OTHER_SUPPLIER_B.NPPES_PROVIDER_COUNTRY,
PHYSICIAN_AND_OTHER_SUPPLIER_B.PROVIDER_TYPE,
PHYSICIAN_AND_OTHER_SUPPLIER_B.MEDICARE_PARTICIPATION_INDICAT,
PHYSICIAN_AND_OTHER_SUPPLIER_B.PLACE_OF_SERVICE,
PHYSICIAN_AND_OTHER_SUPPLIER_B.HCPCS_CODE,
PHYSICIAN_AND_OTHER_SUPPLIER_B.HCPCS_DESCRIPTION,
PHYSICIAN_AND_OTHER_SUPPLIER_B.LINE_SRVC_CNT,
PHYSICIAN_AND_OTHER_SUPPLIER_B.BENE_UNIQUE_CNT,
PHYSICIAN_AND_OTHER_SUPPLIER_B.BENE_DAY_SRVC_CNT,
PHYSICIAN_AND_OTHER_SUPPLIER_B.AVERAGE_MEDICARE_ALLOWED_AMT,
PHYSICIAN_AND_OTHER_SUPPLIER_B.STDEV_MEDICARE_ALLOWED_AMT,
PHYSICIAN_AND_OTHER_SUPPLIER_B.AVERAGE_SUBMITTED_CHRG_AMT,
PHYSICIAN_AND_OTHER_SUPPLIER_B.STDEV_SUBMITTED_CHRG_AMT,
PHYSICIAN_AND_OTHER_SUPPLIER_B.AVERAGE_MEDICARE_PAYMENT_AMT,
PHYSICIAN_AND_OTHER_SUPPLIER_B.STDEV_MEDICARE_PAYMENT_AMT,
PHYSICIAN_AND_OTHER_SUPPLIER_B.LINE_SRVC_CNT/PHYSICIAN_HCPCS_AGGREGATE.LINE_SRVC_CNT
from PHYSICIAN_AND_OTHER_SUPPLIER_B, PHYSICIAN_HCPCS_AGGREGATE where 
PHYSICIAN_HCPCS_AGGREGATE.HCPCS_CODE = PHYSICIAN_AND_OTHER_SUPPLIER_B.HCPCS_CODE and
PHYSICIAN_HCPCS_AGGREGATE.PLACE_OF_SERVICE = PHYSICIAN_AND_OTHER_SUPPLIER_B.PLACE_OF_SERVICE and
PHYSICIAN_HCPCS_AGGREGATE.NPPES_PROVIDER_STATE_DESC = 'Overall' ;
drop table PHYSICIAN_AND_OTHER_SUPPLIER_B;
commit;
CREATE TABLE "PHYSICIAN_AND_OTHER_SUPPLIER" 
   (	"ID" NUMBER, 
   "NPI" VARCHAR2(10 BYTE), 
	"NPPES_PROVIDER_LAST_ORG_NAME" VARCHAR2(70 BYTE), 
	"NPPES_PROVIDER_FIRST_NAME" VARCHAR2(20 BYTE), 
	"NPPES_PROVIDER_MI" VARCHAR2(1 BYTE), 
	"NPPES_CREDENTIALS" VARCHAR2(20 BYTE), 
	"NPPES_PROVIDER_GENDER" VARCHAR2(1 BYTE), 
	"NPPES_ENTITY_CODE" VARCHAR2(1 BYTE), 
	"NPPES_PROVIDER_STREET1" VARCHAR2(55 BYTE), 
	"NPPES_PROVIDER_STREET2" VARCHAR2(55 BYTE), 
	"NPPES_PROVIDER_CITY" VARCHAR2(40 BYTE), 
	"NPPES_PROVIDER_ZIP" VARCHAR2(20 BYTE), 
	"NPPES_PROVIDER_STATE" VARCHAR2(2 BYTE), 
	"NPPES_PROVIDER_COUNTRY" VARCHAR2(2 BYTE), 
	"PROVIDER_TYPE" VARCHAR2(43 BYTE), 
	"MEDICARE_PARTICIPATION_INDICAT" VARCHAR2(1 BYTE), 
	"PLACE_OF_SERVICE" VARCHAR2(1 BYTE), 
	"HCPCS_CODE" VARCHAR2(5 BYTE), 
	"HCPCS_DESCRIPTION" VARCHAR2(30 BYTE), 
	"LINE_SRVC_CNT" NUMBER(*,0), 
	"BENE_UNIQUE_CNT" NUMBER(*,0), 
	"BENE_DAY_SRVC_CNT" NUMBER(*,0), 
	"AVERAGE_MEDICARE_ALLOWED_AMT" FLOAT(126), 
	"STDEV_MEDICARE_ALLOWED_AMT" FLOAT(126), 
	"AVERAGE_SUBMITTED_CHRG_AMT" FLOAT(126), 
	"STDEV_SUBMITTED_CHRG_AMT" FLOAT(126), 
	"AVERAGE_MEDICARE_PAYMENT_AMT" FLOAT(126), 
	"STDEV_MEDICARE_PAYMENT_AMT" FLOAT(126),
  "LINE_SRVC_PCT" FLOAT(26),
  "SUBMITTED_CHRG_VS_HCPCS_AGGR" FLOAT(26)

   ) ;
   
commit;
insert into PHYSICIAN_AND_OTHER_SUPPLIER
select 
PHYSICIAN_AND_OTHER_SUPPLIER_C.ID,
PHYSICIAN_AND_OTHER_SUPPLIER_C.NPI,
PHYSICIAN_AND_OTHER_SUPPLIER_C.NPPES_PROVIDER_LAST_ORG_NAME,
PHYSICIAN_AND_OTHER_SUPPLIER_C.NPPES_PROVIDER_FIRST_NAME,
PHYSICIAN_AND_OTHER_SUPPLIER_C.NPPES_PROVIDER_MI,
PHYSICIAN_AND_OTHER_SUPPLIER_C.NPPES_CREDENTIALS,
PHYSICIAN_AND_OTHER_SUPPLIER_C.NPPES_PROVIDER_GENDER,
PHYSICIAN_AND_OTHER_SUPPLIER_C.NPPES_ENTITY_CODE,
PHYSICIAN_AND_OTHER_SUPPLIER_C.NPPES_PROVIDER_STREET1,
PHYSICIAN_AND_OTHER_SUPPLIER_C.NPPES_PROVIDER_STREET2,
PHYSICIAN_AND_OTHER_SUPPLIER_C.NPPES_PROVIDER_CITY,
PHYSICIAN_AND_OTHER_SUPPLIER_C.NPPES_PROVIDER_ZIP,
PHYSICIAN_AND_OTHER_SUPPLIER_C.NPPES_PROVIDER_STATE,
PHYSICIAN_AND_OTHER_SUPPLIER_C.NPPES_PROVIDER_COUNTRY,
PHYSICIAN_AND_OTHER_SUPPLIER_C.PROVIDER_TYPE,
PHYSICIAN_AND_OTHER_SUPPLIER_C.MEDICARE_PARTICIPATION_INDICAT,
PHYSICIAN_AND_OTHER_SUPPLIER_C.PLACE_OF_SERVICE,
PHYSICIAN_AND_OTHER_SUPPLIER_C.HCPCS_CODE,
PHYSICIAN_AND_OTHER_SUPPLIER_C.HCPCS_DESCRIPTION,
PHYSICIAN_AND_OTHER_SUPPLIER_C.LINE_SRVC_CNT,
PHYSICIAN_AND_OTHER_SUPPLIER_C.BENE_UNIQUE_CNT,
PHYSICIAN_AND_OTHER_SUPPLIER_C.BENE_DAY_SRVC_CNT,
PHYSICIAN_AND_OTHER_SUPPLIER_C.AVERAGE_MEDICARE_ALLOWED_AMT,
PHYSICIAN_AND_OTHER_SUPPLIER_C.STDEV_MEDICARE_ALLOWED_AMT,
PHYSICIAN_AND_OTHER_SUPPLIER_C.AVERAGE_SUBMITTED_CHRG_AMT,
PHYSICIAN_AND_OTHER_SUPPLIER_C.STDEV_SUBMITTED_CHRG_AMT,
PHYSICIAN_AND_OTHER_SUPPLIER_C.AVERAGE_MEDICARE_PAYMENT_AMT,
PHYSICIAN_AND_OTHER_SUPPLIER_C.STDEV_MEDICARE_PAYMENT_AMT,
PHYSICIAN_AND_OTHER_SUPPLIER_C.LINE_SRVC_PCT,
PHYSICIAN_AND_OTHER_SUPPLIER_C.AVERAGE_SUBMITTED_CHRG_AMT/PHYSICIAN_HCPCS_AGGREGATE.AVERAGE_SUBMITTED_CHRG_AMT
from PHYSICIAN_AND_OTHER_SUPPLIER_C, PHYSICIAN_HCPCS_AGGREGATE where
PHYSICIAN_AND_OTHER_SUPPLIER_C.HCPCS_CODE = PHYSICIAN_HCPCS_AGGREGATE.HCPCS_CODE and
PHYSICIAN_AND_OTHER_SUPPLIER_C.PLACE_OF_SERVICE = PHYSICIAN_HCPCS_AGGREGATE.PLACE_OF_SERVICE and
PHYSICIAN_AND_OTHER_SUPPLIER_C.NPPES_PROVIDER_STATE = PHYSICIAN_HCPCS_AGGREGATE.NPPES_PROVIDER_STATE_DESC;
drop table PHYSICIAN_AND_OTHER_SUPPLIER_C;
commit;

