update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'AL'
where NPPES_PROVIDER_STATE_DESC = 'Alabama';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'AK'
where NPPES_PROVIDER_STATE_DESC = 'Alaska';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'AS'
where NPPES_PROVIDER_STATE_DESC = 'American Samoa';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'AZ'
where NPPES_PROVIDER_STATE_DESC = 'Arizona';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'AR'
where NPPES_PROVIDER_STATE_DESC = 'Arkansas';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'AA'
where NPPES_PROVIDER_STATE_DESC = 'Armed Forces Central/South America';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'AE'
where NPPES_PROVIDER_STATE_DESC = 'Armed Forces Europe';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'AP'
where NPPES_PROVIDER_STATE_DESC = 'Armed Forces Pacific';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'CA'
where NPPES_PROVIDER_STATE_DESC = 'California';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'CO'
where NPPES_PROVIDER_STATE_DESC = 'Colorado';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'CT'
where NPPES_PROVIDER_STATE_DESC = 'Connecticut';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'DE'
where NPPES_PROVIDER_STATE_DESC = 'Delaware';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'DC'
where NPPES_PROVIDER_STATE_DESC = 'District of Columbia';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'FL'
where NPPES_PROVIDER_STATE_DESC = 'Florida';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'ZZ'
where NPPES_PROVIDER_STATE_DESC = 'Foreign Country';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'GA'
where NPPES_PROVIDER_STATE_DESC = 'Georgia';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'GU'
where NPPES_PROVIDER_STATE_DESC = 'Guam';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'HI'
where NPPES_PROVIDER_STATE_DESC = 'Hawaii';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'ID'
where NPPES_PROVIDER_STATE_DESC = 'Idaho';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'IL'
where NPPES_PROVIDER_STATE_DESC = 'Illinois';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'IN'
where NPPES_PROVIDER_STATE_DESC = 'Indiana';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'IA'
where NPPES_PROVIDER_STATE_DESC = 'Iowa';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'KS'
where NPPES_PROVIDER_STATE_DESC = 'Kansas';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'KY'
where NPPES_PROVIDER_STATE_DESC = 'Kentucky';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'LA'
where NPPES_PROVIDER_STATE_DESC = 'Louisiana';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'ME'
where NPPES_PROVIDER_STATE_DESC = 'Maine';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'MD'
where NPPES_PROVIDER_STATE_DESC = 'Maryland';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'MA'
where NPPES_PROVIDER_STATE_DESC = 'Massachusetts';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'MI'
where NPPES_PROVIDER_STATE_DESC = 'Michigan';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'MN'
where NPPES_PROVIDER_STATE_DESC = 'Minnesota';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'MS'
where NPPES_PROVIDER_STATE_DESC = 'Mississippi';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'MO'
where NPPES_PROVIDER_STATE_DESC = 'Missouri';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'MT'
where NPPES_PROVIDER_STATE_DESC = 'Montana';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'NE'
where NPPES_PROVIDER_STATE_DESC = 'Nebraska';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'NV'
where NPPES_PROVIDER_STATE_DESC = 'Nevada';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'NH'
where NPPES_PROVIDER_STATE_DESC = 'New Hampshire';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'NJ'
where NPPES_PROVIDER_STATE_DESC = 'New Jersey';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'NM'
where NPPES_PROVIDER_STATE_DESC = 'New Mexico';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'NY'
where NPPES_PROVIDER_STATE_DESC = 'New York';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'NC'
where NPPES_PROVIDER_STATE_DESC = 'North Carolina';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'ND'
where NPPES_PROVIDER_STATE_DESC = 'North Dakota';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'MP'
where NPPES_PROVIDER_STATE_DESC = 'North Mariana Islands';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'OH'
where NPPES_PROVIDER_STATE_DESC = 'Ohio';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'OK'
where NPPES_PROVIDER_STATE_DESC = 'Oklahoma';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'OR'
where NPPES_PROVIDER_STATE_DESC = 'Oregon';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'PA'
where NPPES_PROVIDER_STATE_DESC = 'Pennsylvania';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'PR'
where NPPES_PROVIDER_STATE_DESC = 'Puerto Rico';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'RI'
where NPPES_PROVIDER_STATE_DESC = 'Rhode Island';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'SC'
where NPPES_PROVIDER_STATE_DESC = 'South Carolina';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'SD'
where NPPES_PROVIDER_STATE_DESC = 'South Dakota';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'TN'
where NPPES_PROVIDER_STATE_DESC = 'Tennessee';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'TX'
where NPPES_PROVIDER_STATE_DESC = 'Texas';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'XX'
where NPPES_PROVIDER_STATE_DESC = 'Unknown';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'UT'
where NPPES_PROVIDER_STATE_DESC = 'Utah';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'VT'
where NPPES_PROVIDER_STATE_DESC = 'Vermont';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'VI'
where NPPES_PROVIDER_STATE_DESC = 'Virgin Islands';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'VA'
where NPPES_PROVIDER_STATE_DESC = 'Virginia';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'WA'
where NPPES_PROVIDER_STATE_DESC = 'Washington';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'WV'
where NPPES_PROVIDER_STATE_DESC = 'West Virginia';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'WI'
where NPPES_PROVIDER_STATE_DESC = 'Wisconsin';

update PHYSICIAN_HCPCS_AGGREGATE 
set NPPES_PROVIDER_STATE_DESC = 'WY'
where NPPES_PROVIDER_STATE_DESC = 'Wyoming';

commit;
